---
version: ~> 1.0

os: linux
dist: bionic

language: ruby

install:
  - gem install awesome_bot

script:
  - awesome_bot README.md --allow-dupe --allow-redirect --white-list "bestpractical.com/rt,mogilefs,harding,archipel,linuxcontainers,spiceworks"
